name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  phpstan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: php-actions/composer@v5
      with:
        php_version: 7.3

    - name: PHPStan Static Analysis
      uses: php-actions/phpstan@v2
      with:
        php_version: 7.3
        path: src/

  phpunit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: php-actions/composer@v5
      with:
        php_version: 7.3

    - name: Run PHPUnit tests
      uses: php-actions/phpunit@v2
      with:
        version: 9.5
        php_version: 7.3
        configuration: phpunit.xml.dist

  phpcs:
    runs-on: ubuntu-latest

    steps:
    - name: Setup PHP Action
      uses: shivammathur/setup-php@2.11.0
      with:
        php-version: '7.3'

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: PHPCS check
      run: |
        composer install
        bin/phpcs
