name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  phpstan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: php-actions/composer@v5
      with:
        php_version: 7.3

    - name: PHPStan Static Analysis
      uses: php-actions/phpstan@v2
      with:
        php_version: 7.3
        path: src/

    - name: Run PHPUnit tests
      uses: php-actions/phpunit@v2
      with:
        version: 9.5
        php_version: 7.3
        configuration: phpunit.xml.dist

